- .gitignore
- README.md
- helsinki/login/theme.properties
- Adds the initial helsinki theme. This theme currently exists the `keycloak` theme.
- Adds instructions into README for setting up a local environment for testing this theme
> OM-730 | Initial theme

- .gitignore
- CHANGELOG.md
- helsinki/login/theme.properties
- package-lock.json
- package.json
- sass/hds.scss
This integrates the `hds-core` library. Currently there are two components of interest: `Button` and `TextInput`. The latter couldn't be integrated easily so I omitted it. The `Button` component doesn't work completely out of the box either, because by default keycloak uses `<input type="submit" />` instead of a `<button />` and HDS does not support this by default.
I took inspiration from here: https://github.com/UKHomeOffice/keycloak-theme-govuk
The approach is very lightweight which I liked because:
- Keycloak will release a React version in 2021
- Keycloak's future roles in the Helsinki org are not clear entirely
I decided to include `scss` because it's in the official stack, but we could have done without for now as well.
> OM-730 | Integrate hds-core

- helsinki/login/messages/messages_en.properties
- helsinki/login/register.ftl
- helsinki/login/resources/js/customRegistrationValidation.js
- helsinki/login/theme.properties
- sass/custom.scss
These changes add an initial version of the registration page
Errors still need to be presented inline. I'll do this in another PR in order to limit the amount of changes for a single PR.
**Custom field for acknowledging privacy policy**  
I've added a custom field that I enforce by adding an extra validation phase. Now, instead of a single validation on the server, a pre-validation is completed in the browser with the help of JS.
Note that I implemented this functionality in "Vanilla JS". I attempted to avoid external dependencies in order to keep the project lightweight. I also think that we should avoid adding to the custom JS layer if possible, so I didn't want to spend a lot of effort setting something up we shouldn't, in my opinion, use that much.
I implemented the JS to the best of …
> OM-730 | Add new account

- CHANGELOG.md
- helsinki/login/register.ftl
- helsinki/login/template.ftl
- helsinki/login/theme.properties
- package.json
- sass/custom.scss
- sass/hds-overrides.scss
- sass/hds.scss
- sass/keycloak-overrides.scss
- Adds inline errors to the registration form
- Fixes the icon that is used for checkbox (previously a html char was used)
> OM-730 | Add inline erros

- .editorconfig
- helsinki/login/login.ftl
- helsinki/login/resources/js/customRegistrationValidation.js
- helsinki/login/theme.properties
- sass/custom.scss
- sass/keycloak-overrides.scss
* Adds `.editorconfig`
* Fixes styles for forgot password link
* Fixes error caused by script assuming it could always find elements
> OM-730 | Correctly style forgot password link

- helsinki/login/messages/messages_en.properties
- helsinki/login/template.ftl
- helsinki/login/theme.properties
- sass/hds-overrides.scss
Originally these notifications were meant to be replaced with new views, e.g.
But I couldn't find any default template variables which would allow me to deduce when we've last visited the password reset view. So, instead of a view, we'll stick to the notifications keycloak has by default.
Because keycloak has a single generic message for all sent emails (at least password reset and account creation), we've had to replace the original string with one that takes this into account.
> OM-730 | Add styles for form feedback

- helsinki/login/login-update-password.ftl
- helsinki/login/login-verify-email.ftl
- helsinki/login/template.ftl
- sass/custom.scss
- sass/hds-overrides.scss
- sass/keycloak-overrides.scss
* Removes email resend button from verify email template
* Generally targets `a` and `p` elements with theme specific styles
* Fixes left aligned `input[type="button"]` on Firefox
* Removes description from password update page that repeated content
> OM-730 | Various fixes

- README.md
- scripts/config.js
The previous file was tied to a personal Google account. The new file
is owned by an account that's managed by the executive office.
This change also includes documentation about the translation setup
generally as this approach for managing translations was officially
adopted.
> OM-730 | Change translation source spreadsheet

- helsinki/login/resources/js/inputReset.js
- helsinki/login/theme.properties
If the user submits a form with inline errors (registration form) with incorrect inputs, errors will be rendered in conjunction with those inputs that have incorrect data. Previously these errors were retained until the user submitted the form again.
After these changes, the errors will be hidden once the user focuses an erroneous input.
> HP-108 | Hide errors when user focuses input

- sass/custom.scss
- sass/keycloak-overrides.scss
- sass/theme.scss
Decreases padding for the containing element and arranges button rows as columns instead.
> HP-108 | Improve UX on mobile

- sass/hds/hds-overrides.scss
Some buttons received a margin unintentionally due to the way we are
using hds-button__label.
> Fix some skewed buttons

- helsinki/account/theme.properties
Locally the case didn't matter, but on the server it results in an not
found error.
> Fix sign out not working in test server

- CHANGELOG.md
- helsinki/account/account.ftl
For some reason, in this view, the error a user receives when trying to
change their email to one that's already attached to an account, is not
a field level error, but a "global error". This behaviour is different
compared to the registration form. For this reason, we can't omit the
messages element from the account editing page.
For now, errors are shown twice in the view. I checked with the
assigned designer that this was the behaviour we preferred.
> Fix missing email already exists error

- helsinki/email/messages/messages_en.properties
- helsinki/email/messages/messages_fi.properties
Fixed typos in the email templates which caused reset password link not to render when language is English.
Fixed also another typo in the Finnish template.
> HP-9: Fix link to reset password

- .prettierrc
- README.md
- helsinki/login/register.ftl
- helsinki/login/resources/css/hs-login.css
- helsinki/login/resources/js/customRegistrationValidation.js
- helsinki/login/resources/js/profileCreationValidation.js
- helsinki/login/save-profile-confirm-dialog.ftl
- helsinki/login/update-profile-confirm-dialog.ftl
- sass/login/custom.scss
Forms whose ids are used in javascript to handle submitting, validation, etc must have element ids that are not same as in the base theme. Otherwise forms that are not in overwritten in Helsinki theme might not work because js-files are anyway added to the HTML output.
Changed element ids that are used in js-files and are same in Helsinki theme and base theme.
> HP-865 make form ids unique

- helsinki/login/messages/messages_en.properties
- helsinki/login/messages/messages_fi.properties
- helsinki/login/messages/messages_sv.properties
- helsinki/login/resources/js/profileCreationValidation.js
- helsinki/login/verification-code.ftl
This PR includes the form where user inserts the verification code received via email. The verification code can include only numbers and the value is "cleaned" when submitted. This makes copying the code from email easier as copying might include spaces invisible to user.
> HP-914: email verification form

- helsinki/email/html/email-verification-with-code.ftl
- helsinki/email/html/template.ftl
- helsinki/email/messages/messages_en.properties
- helsinki/email/messages/messages_fi.properties
- helsinki/email/messages/messages_sv.properties
- helsinki/email/text/email-verification-with-code.ftl
- helsinki/email/theme.properties
Email templates for the verification codes. Created also a common base template file for these and future emails.
The images are now stored in a cloud service, because right now Keycloak cannot pass url.resourcesPath to email templates, so urls referring to the server's domain cannot be created.
> HP-940: verification emails

- helsinki/login/messages/messages_en.properties
- helsinki/login/messages/messages_fi.properties
- helsinki/login/messages/messages_sv.properties
Just added translation keys for saml.post-form.title and message
The translated view:
> HP-1069: Translated "Authentication redirect"

- helsinki/login/login.ftl
- helsinki/login/theme.properties
Zocial was removed from Keycloak and started to produce 404 errors in helsinki-theme.
Removed all references and usages.
Note: Social logins are disabled on not visible anywhere in Helsinki Tunnistus.
> HP-1280 removee Zocial

- helsinki/email/html/template.ftl
If baseUrl is missing the default value will be an empty string.
This is just a temporary error mitigation and doesn't make the images work if the baseUrl is missing.
> Prevent template error when baseUrl is missing

- helsinki/login/messages/messages_en.properties
- helsinki/login/messages/messages_fi.properties
- helsinki/login/messages/messages_sv.properties
Urls copied from Profile UI.
There still is no English version, so using Finnish instead.
> HP-1438: Updated the broken urls for Privacy policy links.

- helsinki/login/resources/css/hds.css
- helsinki/login/resources/css/hs-login.css
- helsinki/login/resources/css/shared.css
- helsinki/login/theme.properties
- sass/hds/keycloak-overrides.scss
- sass/login/keycloak-overrides.scss
- sass/shared/custom.scss
- sass/shared/keycloak-overrides.scss
Removed import from theme.properties
Copied actually used common styles to shared/keycloak-overrides.scss
Copied actually used login styles to login/keycloak-overrides.scss
Recreated .css files with build script.
> HP-1499: Remove patternfly usage

- helsinki/login/service-connection-confirm-form.ftl
The important part in this version is the contents of the form. It includes two buttons with correct names and values. Everything else, including any texts and styling, is missing.
Replaces #89.
> Skeleton for service connection confirmation form

- helsinki/login/service-connection-confirm-form.ftl
The `serviceName` variable contains a simple string. The `serviceAllowedData` variable contains a sequence of strings. All the strings are readily localized for the current language.
After this PR this template can be made pretty and to include the correct static texts.
> HP-1592 Example for dynamic service data in service connection form

- helsinki/login/service-connection-confirm-form.ftl
Let's use the full term, allowed data fields, everywhere.
> Rename allowed data fields attribute

- helsinki/login/messages/messages_en.properties
- helsinki/login/messages/messages_fi.properties
- helsinki/login/messages/messages_sv.properties
- helsinki/login/unallowed-session-login-method-info.ftl
This is a simple info view, dedicated for informing the user that the session's current login method is not allowed by the client they are trying to authenticate with.
> Add unallowed-session-login-method-info.ftl

- helsinki/login/register.ftl
The username field can be removed from the registration template by setting the `noUsername` attribute to `true`.
> Add flag for removing the username in registration template

- helsinki/login/login.ftl
The login methods that a client supports are listed in its configuration. That configuration is now used to exclude parts of the login form, showing only the relevant parts for the supported login methods.
This commit doesn't modify the styling of the elements. Only the logic is included here.
> HP-1017 Hide login methods that the current client doesn't support
